rethlocal:
  type: synthetic
  # token: "0x123" # Collateral/vault address. Required for collateral types
  owner: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266" # Anvil account[0] (from standard test mnemonic)
  # mailbox and ISM addresses will be filled after deployment
  # mailbox: "TBD"
  # interchainSecurityModule: "TBD"
  # interchainGasPaymaster: "0x123" # Optional interchainGasPaymaster address
  # isNft: true # If the token is an NFT (ERC721), set to true
  # You can optionally set the token metadata
  name: "wTIA"
  symbol: "TIA"
  decimals: 6
  # totalSupply: 10000000
