// @generated
// This file is @generated by prost-build.
/// EventTokenForwarded is emitted when a token is forwarded.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventTokenForwarded {
    /// forward_addr is the forwarding address.
    #[prost(string, tag="1")]
    pub forward_addr: ::prost::alloc::string::String,
    /// token_id is the Hyperlane token identifier.
    #[prost(string, tag="2")]
    pub token_id: ::prost::alloc::string::String,
    /// denom is the token denomination.
    #[prost(string, tag="3")]
    pub denom: ::prost::alloc::string::String,
    /// amount is the amount forwarded.
    #[prost(string, tag="4")]
    pub amount: ::prost::alloc::string::String,
    /// message_id is the Hyperlane message ID.
    #[prost(string, tag="5")]
    pub message_id: ::prost::alloc::string::String,
}
/// GenesisState defines the forwarding module's genesis state.
/// The module is stateless - funds are tracked by the bank module at derived addresses.
///
/// Empty - module has no persistent state beyond what bank tracks.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GenesisState {
}
/// QueryDeriveForwardingAddressRequest is the request for DeriveForwardingAddress.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryDeriveForwardingAddressRequest {
    /// dest_domain is the destination chain domain ID.
    #[prost(uint32, tag="1")]
    pub dest_domain: u32,
    /// dest_recipient is the recipient on destination chain (32 bytes, hex-encoded, 0x prefix optional).
    #[prost(string, tag="2")]
    pub dest_recipient: ::prost::alloc::string::String,
    /// token_id is the hex-encoded token identifier.
    #[prost(string, tag="3")]
    pub token_id: ::prost::alloc::string::String,
}
/// QueryDeriveForwardingAddressResponse is the response for DeriveForwardingAddress.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryDeriveForwardingAddressResponse {
    /// address is the derived forwarding address (bech32).
    #[prost(string, tag="1")]
    pub address: ::prost::alloc::string::String,
}
/// QueryQuoteForwardingFeeRequest is the request for QuoteForwardingFee.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryQuoteForwardingFeeRequest {
    /// dest_domain is the destination chain domain ID.
    #[prost(uint32, tag="1")]
    pub dest_domain: u32,
    /// token_id is the hex-encoded token identifier.
    #[prost(string, tag="2")]
    pub token_id: ::prost::alloc::string::String,
    /// custom_hook_id optionally selects the post-dispatch hook (e.g. an alternative
    /// IGP) the forward will be routed through, so the quote reflects that hook's
    /// price. Hex-encoded (0x prefix optional). Empty => mailbox default hook.
    #[prost(string, tag="3")]
    pub custom_hook_id: ::prost::alloc::string::String,
}
/// QueryQuoteForwardingFeeResponse is the response for QuoteForwardingFee.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryQuoteForwardingFeeResponse {
    /// fee is the estimated Hyperlane IGP fee required for forwarding.
    /// Relayers should set max_igp_fee >= this value (with some buffer for price changes).
    #[prost(message, optional, tag="1")]
    pub fee: ::core::option::Option<super::super::super::cosmos::base::v1beta1::Coin>,
}
/// MsgForward is a permissionless message to trigger token forwarding.
/// Anyone can submit this message to forward tokens at the derived address.
/// The signer (relayer) pays both Celestia gas and Hyperlane IGP fees.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgForward {
    /// signer is the address paying for gas and IGP fees (typically a relayer).
    #[prost(string, tag="1")]
    pub signer: ::prost::alloc::string::String,
    /// forward_addr is the derived forwarding address (bech32).
    #[prost(string, tag="2")]
    pub forward_addr: ::prost::alloc::string::String,
    /// dest_domain is the destination chain domain ID.
    #[prost(uint32, tag="3")]
    pub dest_domain: u32,
    /// dest_recipient is the recipient on destination chain (32 bytes, hex-encoded, 0x prefix optional).
    #[prost(string, tag="4")]
    pub dest_recipient: ::prost::alloc::string::String,
    /// token_id is the hex-encoded token identifier used to derive the per-token forwarding address.
    #[prost(string, tag="5")]
    pub token_id: ::prost::alloc::string::String,
    /// max_igp_fee is the maximum Hyperlane IGP fee the relayer will pay for this forwarding.
    /// The actual fee charged is the lesser of max_igp_fee and the quoted fee.
    /// Required: relayer must provide sufficient fee for the transfer.
    #[prost(message, optional, tag="6")]
    pub max_igp_fee: ::core::option::Option<super::super::super::cosmos::base::v1beta1::Coin>,
    /// custom_hook_id optionally selects the post-dispatch hook (e.g. an alternative
    /// IGP) that handles the interchain gas payment. Empty => mailbox default hook.
    #[prost(string, tag="7")]
    pub custom_hook_id: ::prost::alloc::string::String,
    /// custom_hook_metadata is optional hex-encoded metadata passed to the custom hook.
    #[prost(string, tag="8")]
    pub custom_hook_metadata: ::prost::alloc::string::String,
}
/// MsgForwardResponse is the response for MsgForward.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgForwardResponse {
    /// denom is the token denomination that was forwarded.
    #[prost(string, tag="1")]
    pub denom: ::prost::alloc::string::String,
    /// amount is the amount forwarded.
    #[prost(string, tag="2")]
    pub amount: ::prost::alloc::string::String,
    /// message_id is the Hyperlane message ID.
    #[prost(string, tag="3")]
    pub message_id: ::prost::alloc::string::String,
}
include!("celestia.forwarding.v1.tonic.rs");
// @@protoc_insertion_point(module)
