// @generated
// This file is @generated by prost-build.
/// EventTokenForwarded is emitted when a token is forwarded.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventTokenForwarded {
    /// forward_addr is the forwarding address.
    #[prost(string, tag="1")]
    pub forward_addr: ::prost::alloc::string::String,
    /// denom is the token denomination.
    #[prost(string, tag="2")]
    pub denom: ::prost::alloc::string::String,
    /// amount is the amount forwarded.
    #[prost(string, tag="3")]
    pub amount: ::prost::alloc::string::String,
    /// message_id is the Hyperlane message ID.
    #[prost(string, tag="4")]
    pub message_id: ::prost::alloc::string::String,
    /// success indicates whether the forward succeeded.
    #[prost(bool, tag="5")]
    pub success: bool,
    /// error contains the error message when success=false.
    #[prost(string, tag="6")]
    pub error: ::prost::alloc::string::String,
}
/// EventForwardingComplete is emitted when all tokens at an address are processed.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventForwardingComplete {
    /// forward_addr is the forwarding address.
    #[prost(string, tag="1")]
    pub forward_addr: ::prost::alloc::string::String,
    /// dest_domain is the destination chain domain ID.
    #[prost(uint32, tag="2")]
    pub dest_domain: u32,
    /// dest_recipient is the recipient on destination chain.
    #[prost(string, tag="3")]
    pub dest_recipient: ::prost::alloc::string::String,
    /// tokens_forwarded is the count of successfully forwarded tokens.
    #[prost(uint32, tag="4")]
    pub tokens_forwarded: u32,
    /// tokens_failed is the count of tokens that failed to forward.
    #[prost(uint32, tag="5")]
    pub tokens_failed: u32,
}
/// GenesisState defines the forwarding module's genesis state.
/// The module is stateless - funds are tracked by the bank module at derived addresses.
///
/// Empty - module has no persistent state beyond what bank tracks.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GenesisState {
}
/// QueryDeriveForwardingAddressRequest is the request for DeriveForwardingAddress.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryDeriveForwardingAddressRequest {
    /// dest_domain is the destination chain domain ID.
    #[prost(uint32, tag="1")]
    pub dest_domain: u32,
    /// dest_recipient is the recipient on destination chain (32 bytes, hex-encoded, 0x prefix optional).
    #[prost(string, tag="2")]
    pub dest_recipient: ::prost::alloc::string::String,
}
/// QueryDeriveForwardingAddressResponse is the response for DeriveForwardingAddress.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryDeriveForwardingAddressResponse {
    /// address is the derived forwarding address (bech32).
    #[prost(string, tag="1")]
    pub address: ::prost::alloc::string::String,
}
/// QueryQuoteForwardingFeeRequest is the request for QuoteForwardingFee.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct QueryQuoteForwardingFeeRequest {
    /// dest_domain is the destination chain domain ID.
    #[prost(uint32, tag="1")]
    pub dest_domain: u32,
}
/// QueryQuoteForwardingFeeResponse is the response for QuoteForwardingFee.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryQuoteForwardingFeeResponse {
    /// fee is the estimated Hyperlane IGP fee required for forwarding.
    /// Relayers should set max_igp_fee >= this value (with some buffer for price changes).
    #[prost(message, optional, tag="1")]
    pub fee: ::core::option::Option<super::super::super::cosmos::base::v1beta1::Coin>,
}
/// MsgForward is a permissionless message to trigger token forwarding.
/// Anyone can submit this message to forward tokens at the derived address.
/// The signer (relayer) pays both Celestia gas and Hyperlane IGP fees.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgForward {
    /// signer is the address paying for gas and IGP fees (typically a relayer).
    #[prost(string, tag="1")]
    pub signer: ::prost::alloc::string::String,
    /// forward_addr is the derived forwarding address (bech32).
    #[prost(string, tag="2")]
    pub forward_addr: ::prost::alloc::string::String,
    /// dest_domain is the destination chain domain ID.
    #[prost(uint32, tag="3")]
    pub dest_domain: u32,
    /// dest_recipient is the recipient on destination chain (32 bytes, hex-encoded, 0x prefix optional).
    #[prost(string, tag="4")]
    pub dest_recipient: ::prost::alloc::string::String,
    /// max_igp_fee is the maximum Hyperlane IGP fee the relayer will pay for this forwarding.
    /// The actual fee charged is the lesser of max_igp_fee and the quoted fee.
    /// Required: relayer must provide sufficient fee for the transfer.
    #[prost(message, optional, tag="5")]
    pub max_igp_fee: ::core::option::Option<super::super::super::cosmos::base::v1beta1::Coin>,
}
/// MsgForwardResponse is the response for MsgForward.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgForwardResponse {
    /// results contains the per-token forwarding results.
    #[prost(message, repeated, tag="1")]
    pub results: ::prost::alloc::vec::Vec<ForwardingResult>,
}
/// ForwardingResult contains the result for a single token forward.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ForwardingResult {
    /// denom is the token denomination.
    #[prost(string, tag="1")]
    pub denom: ::prost::alloc::string::String,
    /// amount is the amount forwarded.
    #[prost(string, tag="2")]
    pub amount: ::prost::alloc::string::String,
    /// message_id is the Hyperlane message ID (empty if failed).
    #[prost(string, tag="3")]
    pub message_id: ::prost::alloc::string::String,
    /// success indicates whether the forward succeeded.
    #[prost(bool, tag="4")]
    pub success: bool,
    /// error contains the error message if failed (empty if success).
    #[prost(string, tag="5")]
    pub error: ::prost::alloc::string::String,
}
include!("celestia.forwarding.v1.tonic.rs");
// @@protoc_insertion_point(module)